# Generated by Django 3.0.5 on 2020-05-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0003_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district_id', models.CharField(max_length=100, unique=True)),
                ('time_stamp', models.DateTimeField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.States')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
