# Generated by Django 3.0.5 on 2020-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20200521_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district_id', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'district_history',
            },
        ),
    ]
