# Generated by Django 3.0.5 on 2020-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_districthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_model',
            },
        ),
    ]
