# Generated by Django 3.0.5 on 2020-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
