# Generated by Django 3.0.5 on 2020-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_testmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(upload_to='static/country/images/'),
        ),
    ]
