# Generated by Django 3.0.5 on 2020-07-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_auto_20200628_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('TestModel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='district.TestModel')),
            ],
        ),
    ]
