# Generated by Django 3.0.5 on 2020-07-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0007_testmodel1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel1',
            table='test_model1',
        ),
    ]
