# Generated by Django 3.0.5 on 2020-07-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0008_auto_20200710_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel1',
        ),
    ]
