# Generated by Django 3.0.5 on 2020-07-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0009_delete_testmodel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('testmodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='district.TestModel')),
                ('name1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_model1',
            },
        ),
    ]
