# Generated by Django 3.0.5 on 2020-07-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0011_framework_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
