# Generated by Django 3.0.5 on 2020-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0012_auto_20200719_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('student', models.ManyToManyField(to='district.Student')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
