# Generated by Django 3.0.5 on 2020-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0013_courses_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
