# Generated by Django 3.0.5 on 2020-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0015_auto_20200809_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='1', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('General', 'Upper Caste'), ('Obc', 'Other Backword Class'), ('Sc', 'Scheduled Castes'), ('St', 'Scheduled Tribes')], default='Indian', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
