# Generated by Django 3.0.5 on 2020-09-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0018_auto_20200901_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.Language')),
            ],
            options={
                'db_table': 'languagemaker',
            },
        ),
    ]
