# Generated by Django 3.0.5 on 2020-09-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0019_languagemaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagemaker',
            name='language',
        ),
        migrations.AddField(
            model_name='languagemaker',
            name='framework',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='district.Framework'),
        ),
    ]
