# Generated by Django 3.0.5 on 2020-09-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0021_student_student_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
