# Generated by Django 3.1.1 on 2020-09-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0026_testing_testing1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testing1',
            table='testing1',
        ),
    ]
