# Generated by Django 3.1.1 on 2020-10-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0027_auto_20200930_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='district.selfexample')),
            ],
            options={
                'db_table': 'self_example',
            },
        ),
    ]
