# Generated by Django 3.1.1 on 2020-10-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0028_selfexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfexample',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='district.selfexample'),
        ),
    ]
