# Generated by Django 3.1.1 on 2020-11-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0030_auto_20201004_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
