# Generated by Django 3.1.1 on 2020-11-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0035_model1_model2_model3'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3',
            name='model1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.model1'),
        ),
        migrations.AddField(
            model_name='model3',
            name='model2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.model2'),
        ),
    ]
