# Generated by Django 3.1.1 on 2020-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0041_auto_20201126_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fload_number', models.FloatField(max_length=50)),
                ('decimal_number', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'model5',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student_course', to='district.Courses'),
        ),
    ]
