# Generated by Django 3.1.1 on 2020-12-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0042_auto_20201210_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'check1',
            },
        ),
        migrations.CreateModel(
            name='Check2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
                ('check1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='district.check1')),
            ],
            options={
                'db_table': 'check2',
            },
        ),
    ]
