# Generated by Django 3.1.7 on 2021-03-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0043_check1_check2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_height',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_weight',
        ),
    ]
