# Generated by Django 3.1.7 on 2021-03-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0045_auto_20210319_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='name1',
            field=models.CharField(default='name1', max_length=100),
        ),
    ]
