# Generated by Django 3.1.7 on 2021-03-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0046_add_name1_coloumn_in_Model1'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='name2',
            field=models.CharField(default='name2', max_length=100),
        ),
    ]
