# Generated by Django 3.1.7 on 2021-03-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0047_add_name2_coloumn_in_Model1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'model6',
            },
        ),
    ]
