# Generated by Django 3.1.7 on 2021-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0048_model6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model1',
            name='name1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model1',
            name='name2',
            field=models.CharField(max_length=100),
        ),
    ]
