# Generated by Django 3.1.7 on 2021-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0051_model1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1112',
        ),
    ]
