# Generated by Django 3.1.7 on 2021-05-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0054_historicalstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
