# Generated by Django 3.0.5 on 2020-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
