# Generated by Django 3.0.5 on 2020-06-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_pms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pms',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='country.Country'),
        ),
    ]
