# Generated by Django 3.0.5 on 2020-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_pms_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pm_id', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=5)),
                ('party', models.CharField(max_length=100)),
                ('country_id', models.IntegerField(max_length=10)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pms_history',
            },
        ),
    ]
