# Generated by Django 3.0.5 on 2020-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_pmshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.CharField(max_length=100)),
                ('country_status', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'country_history',
            },
        ),
    ]
