# Generated by Django 3.0.5 on 2020-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_countryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pms',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pmshistory',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pmshistory',
            name='country_id',
            field=models.IntegerField(),
        ),
    ]
