# Generated by Django 3.0.5 on 2020-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20200710_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
