# Generated by Django 3.1.7 on 2021-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20200827_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1112',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
