# Generated by Django 3.1.7 on 2021-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_model1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model222',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
