# Generated by Django 3.1.1 on 2020-11-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
